-- =========================================================================
-- PT. Karsa Ruang Nusantara - N-IMS (Nukarsa Immigration Management System)
-- COMPLETE DATABASE SETUP & SECURITY POLICIES SQL SCRIPT
-- =========================================================================

-- Enable UUID Extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =========================================================================
-- 1. CREATE TABLES
-- =========================================================================

-- A. CMS Content Table (For Landing Page & Translations Editing)
CREATE TABLE IF NOT EXISTS public.cms_content (
    key text PRIMARY KEY,
    value jsonb NOT NULL,
    updated_at timestamp with time zone DEFAULT now()
);

-- B. Booking Tokens Table (Single-use Invitation Links)
CREATE TABLE IF NOT EXISTS public.booking_tokens (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    client_name text NOT NULL,
    client_email text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone DEFAULT (now() + interval '7 days') NOT NULL,
    status text DEFAULT 'active' CHECK (status IN ('active', 'used', 'expired')) NOT NULL,
    used_at timestamp with time zone,
    application_id bigint
);

-- C. Applications Table (Visa & Kitas Registrations)
CREATE TABLE IF NOT EXISTS public.applications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    full_name text NOT NULL,
    passport_number text NOT NULL,
    visa_type text NOT NULL,
    country text,         -- Client's country of origin
    identity_card text,   -- Client's national identity card number
    no_telephone text,    -- Client's telephone / WhatsApp number
    email text,           -- Client's email address
    status text DEFAULT 'Pending' CHECK (status IN ('Pending', 'Verified', 'In Progress', 'Completed', 'Rejected')) NOT NULL,
    booking_token_id uuid REFERENCES public.booking_tokens(id) ON DELETE SET NULL
);

-- Link booking_tokens back to applications for relational integrity
ALTER TABLE public.booking_tokens 
DROP CONSTRAINT IF EXISTS fk_booking_token_application,
ADD CONSTRAINT fk_booking_token_application 
FOREIGN KEY (application_id) REFERENCES public.applications(id) ON DELETE CASCADE;

-- D. Documents Table (Passport File Links - supports multiple files per application)
CREATE TABLE IF NOT EXISTS public.documents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    application_id bigint REFERENCES public.applications(id) ON DELETE CASCADE NOT NULL,
    file_url text NOT NULL,
    doc_type text DEFAULT 'Passport' NOT NULL
);

-- E. Status Updates Table (Audit Logs / History for Admin Center)
CREATE TABLE IF NOT EXISTS public.status_updates (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    application_id bigint REFERENCES public.applications(id) ON DELETE CASCADE NOT NULL,
    status text NOT NULL,
    notes text
);

-- F. Quotations Table (Invoice / Penawaran Harga per Aplikasi)
CREATE TABLE IF NOT EXISTS public.quotations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    application_id bigint REFERENCES public.applications(id) ON DELETE CASCADE NOT NULL,
    amount numeric(15,2) NOT NULL,
    currency text DEFAULT 'IDR' NOT NULL,
    status text DEFAULT 'Draft' CHECK (status IN ('Draft', 'Sent', 'Paid', 'Cancelled')) NOT NULL,
    notes text,
    due_date timestamp with time zone,
    paid_at timestamp with time zone
);

-- G. Token Requests Table (Self-Service Calon Klien)
CREATE TABLE IF NOT EXISTS public.token_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    full_name text NOT NULL,
    email text NOT NULL,
    phone text,
    visa_type text,
    message text,
    status text DEFAULT 'Pending' CHECK (status IN ('Pending', 'Approved', 'Rejected')) NOT NULL,
    admin_notes text
);

-- H. SLA Config Table (Estimasi Waktu Pemrosesan per Jenis Visa)
CREATE TABLE IF NOT EXISTS public.sla_config (
    visa_type text PRIMARY KEY,
    processing_days integer NOT NULL,
    description_en text,
    description_id text
);

-- I. Notification Logs Table (Catatan Notifikasi Terkirim)
CREATE TABLE IF NOT EXISTS public.notification_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    application_id bigint REFERENCES public.applications(id) ON DELETE CASCADE NOT NULL,
    channel text NOT NULL CHECK (channel IN ('email', 'whatsapp', 'system')),
    message text NOT NULL,
    triggered_by text DEFAULT 'admin'
);

-- =========================================================================
-- 2. ENABLE ROW LEVEL SECURITY (RLS) ON ALL TABLES
-- =========================================================================
ALTER TABLE public.cms_content ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.booking_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.status_updates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quotations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.token_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sla_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notification_logs ENABLE ROW LEVEL SECURITY;

-- =========================================================================
-- 3. DEFINE RLS POLICIES
-- =========================================================================

-- --- cms_content Policies ---
DROP POLICY IF EXISTS "Allow public read access to cms_content" ON public.cms_content;
CREATE POLICY "Allow public read access to cms_content" 
ON public.cms_content FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow admin all access to cms_content" ON public.cms_content;
CREATE POLICY "Allow admin all access to cms_content" 
ON public.cms_content FOR ALL TO authenticated USING (true) WITH CHECK (true);


-- --- booking_tokens Policies ---
DROP POLICY IF EXISTS "Allow public read of active/valid booking_tokens" ON public.booking_tokens;
CREATE POLICY "Allow public read of active/valid booking_tokens" 
ON public.booking_tokens FOR SELECT 
USING (status = 'active' AND expires_at > now());

DROP POLICY IF EXISTS "Allow public update of booking_tokens (claim token)" ON public.booking_tokens;
CREATE POLICY "Allow public update of booking_tokens (claim token)" 
ON public.booking_tokens FOR UPDATE 
USING (status = 'active' AND expires_at > now())
WITH CHECK (status = 'used');

DROP POLICY IF EXISTS "Allow admin all access to booking_tokens" ON public.booking_tokens;
CREATE POLICY "Allow admin all access to booking_tokens" 
ON public.booking_tokens FOR ALL TO authenticated USING (true) WITH CHECK (true);


-- --- applications Policies ---
DROP POLICY IF EXISTS "Allow public to insert application" ON public.applications;
CREATE POLICY "Allow public to insert application" 
ON public.applications FOR INSERT 
WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public to select their own submitted applications" ON public.applications;
CREATE POLICY "Allow public to select their own submitted applications" 
ON public.applications FOR SELECT 
USING (true);

DROP POLICY IF EXISTS "Allow admin all access to applications" ON public.applications;
CREATE POLICY "Allow admin all access to applications" 
ON public.applications FOR ALL TO authenticated USING (true) WITH CHECK (true);


-- --- documents Policies ---
DROP POLICY IF EXISTS "Allow public to insert document" ON public.documents;
CREATE POLICY "Allow public to insert document" 
ON public.documents FOR INSERT 
WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public to read documents" ON public.documents;
CREATE POLICY "Allow public to read documents"
ON public.documents FOR SELECT
USING (true);

DROP POLICY IF EXISTS "Allow admin all access to documents" ON public.documents;
CREATE POLICY "Allow admin all access to documents" 
ON public.documents FOR ALL TO authenticated USING (true) WITH CHECK (true);


-- --- status_updates Policies ---
DROP POLICY IF EXISTS "Allow public to read audit logs of their own application" ON public.status_updates;
CREATE POLICY "Allow public to read audit logs of their own application" 
ON public.status_updates FOR SELECT 
USING (true);

DROP POLICY IF EXISTS "Allow admin all access to status_updates" ON public.status_updates;
CREATE POLICY "Allow admin all access to status_updates" 
ON public.status_updates FOR ALL TO authenticated USING (true) WITH CHECK (true);


-- --- quotations Policies ---
DROP POLICY IF EXISTS "Allow public to read their quotation" ON public.quotations;
CREATE POLICY "Allow public to read their quotation"
ON public.quotations FOR SELECT
USING (true);

DROP POLICY IF EXISTS "Allow admin all access to quotations" ON public.quotations;
CREATE POLICY "Allow admin all access to quotations" 
ON public.quotations FOR ALL TO authenticated USING (true) WITH CHECK (true);


-- --- token_requests Policies ---
DROP POLICY IF EXISTS "Allow public to insert token_requests" ON public.token_requests;
CREATE POLICY "Allow public to insert token_requests"
ON public.token_requests FOR INSERT
WITH CHECK (true);

DROP POLICY IF EXISTS "Allow admin all access to token_requests" ON public.token_requests;
CREATE POLICY "Allow admin all access to token_requests" 
ON public.token_requests FOR ALL TO authenticated USING (true) WITH CHECK (true);


-- --- sla_config Policies ---
DROP POLICY IF EXISTS "Allow public to read sla_config" ON public.sla_config;
CREATE POLICY "Allow public to read sla_config"
ON public.sla_config FOR SELECT
USING (true);

DROP POLICY IF EXISTS "Allow admin all access to sla_config" ON public.sla_config;
CREATE POLICY "Allow admin all access to sla_config" 
ON public.sla_config FOR ALL TO authenticated USING (true) WITH CHECK (true);


-- --- notification_logs Policies ---
DROP POLICY IF EXISTS "Allow public to read notification_logs" ON public.notification_logs;
CREATE POLICY "Allow public to read notification_logs"
ON public.notification_logs FOR SELECT
USING (true);

DROP POLICY IF EXISTS "Allow admin all access to notification_logs" ON public.notification_logs;
CREATE POLICY "Allow admin all access to notification_logs" 
ON public.notification_logs FOR ALL TO authenticated USING (true) WITH CHECK (true);


-- =========================================================================
-- 4. CONFIGURE STORAGE BUCKET & RLS POLICIES FOR FILES
-- =========================================================================
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types) 
VALUES (
  'nukarsa-files', 
  'nukarsa-files', 
  true, 
  10485760,
  ARRAY['image/png', 'image/jpeg', 'image/jpg', 'application/pdf']
) 
ON CONFLICT (id) DO UPDATE 
SET public = true, file_size_limit = 10485760;

DROP POLICY IF EXISTS "Allow public uploads to nukarsa-files" ON storage.objects;
CREATE POLICY "Allow public uploads to nukarsa-files"
ON storage.objects FOR INSERT
TO public
WITH CHECK (bucket_id = 'nukarsa-files');

DROP POLICY IF EXISTS "Allow public read from nukarsa-files" ON storage.objects;
CREATE POLICY "Allow public read from nukarsa-files"
ON storage.objects FOR SELECT
TO public
USING (bucket_id = 'nukarsa-files');

DROP POLICY IF EXISTS "Allow admin all access to nukarsa-files" ON storage.objects;
CREATE POLICY "Allow admin all access to nukarsa-files"
ON storage.objects FOR ALL
TO authenticated
USING (bucket_id = 'nukarsa-files')
WITH CHECK (bucket_id = 'nukarsa-files');

-- =========================================================================
-- 5. ENABLE REALTIME REPLICATION ON KEY TABLES
-- =========================================================================
ALTER PUBLICATION supabase_realtime ADD TABLE public.applications;
ALTER PUBLICATION supabase_realtime ADD TABLE public.booking_tokens;
ALTER PUBLICATION supabase_realtime ADD TABLE public.status_updates;
ALTER PUBLICATION supabase_realtime ADD TABLE public.quotations;
ALTER PUBLICATION supabase_realtime ADD TABLE public.token_requests;

-- =========================================================================
-- 6. SEED DEFAULT SLA DATA
-- =========================================================================
INSERT INTO public.sla_config (visa_type, processing_days, description_en, description_id) VALUES
  ('Visa VoA',                3,  'Visa on Arrival processed within 3 working days.',         'Visa VoA diproses dalam 3 hari kerja.'),
  ('Visa C2',                 7,  'Business meeting visa processed within 7 working days.',    'Visa bisnis C2 diproses dalam 7 hari kerja.'),
  ('Visa D2',                14,  'Investor visa processed within 14 working days.',           'Visa investor D2 diproses dalam 14 hari kerja.'),
  ('Working KITAS (E23)',    30,  'Working KITAS takes approximately 30 working days.',        'KITAS Kerja diproses sekitar 30 hari kerja.'),
  ('Investment KITAS (E28A)',30,  'Investment KITAS takes approximately 30 working days.',     'KITAS Investasi diproses sekitar 30 hari kerja.'),
  ('Bridging Visa',           7,  'Bridging visa processed within 7 working days.',            'Visa Bridging diproses dalam 7 hari kerja.')
ON CONFLICT (visa_type) DO UPDATE
  SET processing_days = EXCLUDED.processing_days,
      description_en  = EXCLUDED.description_en,
      description_id  = EXCLUDED.description_id;

-- =========================================================================
-- 7. MIGRATION HELPERS (run if tables already exist in production)
-- =========================================================================
-- ALTER TABLE public.applications ADD COLUMN IF NOT EXISTS no_telephone text;
-- ALTER TABLE public.applications ADD COLUMN IF NOT EXISTS email text;
