-- =========================================================================
-- PT. Karsa Ruang Nusantara - N-IMS (Nukarsa Immigration Management System)
-- COMPLETE DATABASE SETUP & SECURITY POLICIES SQL SCRIPT
-- =========================================================================

-- Enable UUID Extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =========================================================================
-- 1. CREATE TABLES
-- =========================================================================

-- A. CMS Content Table (For Landing Page & Translations Editing)
CREATE TABLE IF NOT EXISTS public.cms_content (
    key text PRIMARY KEY,
    value jsonb NOT NULL,
    updated_at timestamp with time zone DEFAULT now()
);

-- B. Booking Tokens Table (Single-use Invitation Links)
CREATE TABLE IF NOT EXISTS public.booking_tokens (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    client_name text NOT NULL,
    client_email text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone DEFAULT (now() + interval '7 days') NOT NULL,
    status text DEFAULT 'active' CHECK (status IN ('active', 'used', 'expired')) NOT NULL,
    used_at timestamp with time zone,
    application_id bigint
);

-- C. Applications Table (Visa & Kitas Registrations)
CREATE TABLE IF NOT EXISTS public.applications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    full_name text NOT NULL,
    passport_number text NOT NULL,
    visa_type text NOT NULL,
    country text, -- Client's country of origin
    identity_card text, -- Client's national identity card number
    status text DEFAULT 'Pending' CHECK (status IN ('Pending', 'Verified', 'In Progress', 'Completed', 'Rejected')) NOT NULL,
    booking_token_id uuid REFERENCES public.booking_tokens(id) ON DELETE SET NULL
);

-- Link booking_tokens back to applications for relational integrity
ALTER TABLE public.booking_tokens 
DROP CONSTRAINT IF EXISTS fk_booking_token_application,
ADD CONSTRAINT fk_booking_token_application 
FOREIGN KEY (application_id) REFERENCES public.applications(id) ON DELETE CASCADE;

-- D. Documents Table (Passport File Links)
CREATE TABLE IF NOT EXISTS public.documents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    application_id bigint REFERENCES public.applications(id) ON DELETE CASCADE NOT NULL,
    file_url text NOT NULL,
    doc_type text DEFAULT 'Passport' NOT NULL
);

-- E. Status Updates Table (Audit Logs / History for Admin Center)
CREATE TABLE IF NOT EXISTS public.status_updates (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    application_id bigint REFERENCES public.applications(id) ON DELETE CASCADE NOT NULL,
    status text NOT NULL,
    notes text
);

-- =========================================================================
-- 2. ENABLE ROW LEVEL SECURITY (RLS) ON ALL TABLES
-- =========================================================================
ALTER TABLE public.cms_content ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.booking_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.status_updates ENABLE ROW LEVEL SECURITY;

-- =========================================================================
-- 3. DEFINE RLS POLICIES
-- =========================================================================

-- --- cms_content Policies ---
DROP POLICY IF EXISTS "Allow public read access to cms_content" ON public.cms_content;
CREATE POLICY "Allow public read access to cms_content" 
ON public.cms_content FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow admin all access to cms_content" ON public.cms_content;
CREATE POLICY "Allow admin all access to cms_content" 
ON public.cms_content FOR ALL TO authenticated USING (true) WITH CHECK (true);


-- --- booking_tokens Policies ---
-- Allow public select ONLY if the token is active and not expired
DROP POLICY IF EXISTS "Allow public read of active/valid booking_tokens" ON public.booking_tokens;
CREATE POLICY "Allow public read of active/valid booking_tokens" 
ON public.booking_tokens FOR SELECT 
USING (status = 'active' AND expires_at > now());

-- Allow public to update token to 'used' when booking
DROP POLICY IF EXISTS "Allow public update of booking_tokens (claim token)" ON public.booking_tokens;
CREATE POLICY "Allow public update of booking_tokens (claim token)" 
ON public.booking_tokens FOR UPDATE 
USING (status = 'active' AND expires_at > now())
WITH CHECK (status = 'used');

DROP POLICY IF EXISTS "Allow admin all access to booking_tokens" ON public.booking_tokens;
CREATE POLICY "Allow admin all access to booking_tokens" 
ON public.booking_tokens FOR ALL TO authenticated USING (true) WITH CHECK (true);


-- --- applications Policies ---
-- Allow public to insert applications
DROP POLICY IF EXISTS "Allow public to insert application" ON public.applications;
CREATE POLICY "Allow public to insert application" 
ON public.applications FOR INSERT 
WITH CHECK (true);

-- Allow public to read applications (required for clients checking post-submission status)
DROP POLICY IF EXISTS "Allow public to select their own submitted applications" ON public.applications;
CREATE POLICY "Allow public to select their own submitted applications" 
ON public.applications FOR SELECT 
USING (true);

DROP POLICY IF EXISTS "Allow admin all access to applications" ON public.applications;
CREATE POLICY "Allow admin all access to applications" 
ON public.applications FOR ALL TO authenticated USING (true) WITH CHECK (true);


-- --- documents Policies ---
-- Allow public to insert documents
DROP POLICY IF EXISTS "Allow public to insert document" ON public.documents;
CREATE POLICY "Allow public to insert document" 
ON public.documents FOR INSERT 
WITH CHECK (true);

DROP POLICY IF EXISTS "Allow admin all access to documents" ON public.documents;
CREATE POLICY "Allow admin all access to documents" 
ON public.documents FOR ALL TO authenticated USING (true) WITH CHECK (true);


-- --- status_updates Policies ---
-- Allow public to view status audit logs
DROP POLICY IF EXISTS "Allow public to read audit logs of their own application" ON public.status_updates;
CREATE POLICY "Allow public to read audit logs of their own application" 
ON public.status_updates FOR SELECT 
USING (true);

DROP POLICY IF EXISTS "Allow admin all access to status_updates" ON public.status_updates;
CREATE POLICY "Allow admin all access to status_updates" 
ON public.status_updates FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- =========================================================================
-- 4. CONFIGURE STORAGE BUCKET & RLS POLICIES FOR FILES
-- =========================================================================

-- Create storage bucket if not exists and make it public
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types) 
VALUES (
  'nukarsa-files', 
  'nukarsa-files', 
  true, 
  10485760, -- 10MB limit
  ARRAY['image/png', 'image/jpeg', 'image/jpg', 'application/pdf']
) 
ON CONFLICT (id) DO UPDATE 
SET public = true, file_size_limit = 10485760;

-- RLS Policies on Storage.objects table
-- Allow anyone to upload files to 'nukarsa-files'
DROP POLICY IF EXISTS "Allow public uploads to nukarsa-files" ON storage.objects;
CREATE POLICY "Allow public uploads to nukarsa-files"
ON storage.objects FOR INSERT
TO public
WITH CHECK (bucket_id = 'nukarsa-files');

-- Allow anyone to read files from 'nukarsa-files' bucket (required for publicUrl)
DROP POLICY IF EXISTS "Allow public read from nukarsa-files" ON storage.objects;
CREATE POLICY "Allow public read from nukarsa-files"
ON storage.objects FOR SELECT
TO public
USING (bucket_id = 'nukarsa-files');

-- Allow admin complete dashboard control over storage objects
DROP POLICY IF EXISTS "Allow admin all access to nukarsa-files" ON storage.objects;
CREATE POLICY "Allow admin all access to nukarsa-files"
ON storage.objects FOR ALL
TO authenticated
USING (bucket_id = 'nukarsa-files')
WITH CHECK (bucket_id = 'nukarsa-files');

-- =========================================================================
-- 5. ENABLE REALTIME REPLICATION ON KEY TABLES
-- =========================================================================
-- Added tables to supabase_realtime for realtime replication

ALTER PUBLICATION supabase_realtime ADD TABLE public.applications;
ALTER PUBLICATION supabase_realtime ADD TABLE public.booking_tokens;
ALTER PUBLICATION supabase_realtime ADD TABLE public.status_updates;
